### ISSUE TITLE
Verify imgui default value in bindings

### ISSUE THREAD

**Issue by xposure** [RogueMacro/imgui-beef#1]
ImGui bindings with default, noticed that uv1 is (1, 1), tint is (1,1,1,1) and border = (0,0,0,0)
https://github.com/ocornut/imgui/blob/master/imgui.h#L450

Beef bindings, uv1 = default, tint = default, border = default
https://github.com/RogueMacro/imgui-beef/blob/master/ImGui/src/ImGui.bf#L5884

**Comment by RogueMacro** [comment]
Fixed in d63d136
