### ISSUE TITLE
Unknown Renderer* type in ImGuiImplSDL2

### ISSUE THREAD

**Issue by LauraRozier** [RogueMacro/imgui-beef#11]
There is a small issue with the ImGuiImplSDL2 where it can't find the Renderer type.
Easily fixed by changing  `Renderer* renderer` to `SDL2.SDL.Renderer* renderer`.

It'd probably be best to fix this in the generator, though.

**Comment by RogueMacro** [comment]
Fixed in 8f1d6cb.
