### ISSUE TITLE
Beef 0.43.4 + Visual Studio 2022 undefined reference ImGui_ImplSDL2_*

### ISSUE THREAD

**Issue by maihd** [RogueMacro/imgui-beef#12]
When I compile Beef 0.43.4 example project that use ImGuiImplSDL cause undefined reference. But build CImGui worked for me. Maybe add build script for user?

Step preproduce:
- Beef 0.43.4
- Visual Studio 2022 installed (latest)
- Clone project to BeefLibs
- Create an example projects use ImGuiImplSDL

Fix guide:
- Manually rebuild cimgui with Visual Studio 2022

Proposal:
- Add build script to help newcomer

**Comment by RogueMacro** [comment]
Thanks! Fixed this in the latest release. Simply a spelling error `CMakeLists.txt`. Supposed to be sdl2 and not sdl.

**Comment by maihd** [comment]
You're welcome!
